##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Tue Jul 23 18:35:59 2024

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       example_top.sd
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K325TIFFG900_PKG
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         900.09000000000003 MHz
##                    Time Period:       1111 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41J256m16XX-107
## Data Width: 32
## Time Period: 1111
## Data Mask: 1
##################################################################################################

set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_n[*]} ]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_p[*]} ]
          
#create_clock -period 4.999 [get_ports sys_clk_i]
          
############## NET - IOSTANDARD ##################


