# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/danie/Dropbox/physics/UdeC/FPGA_UBB/Final_FPGA_UBB/Genesys2_VideoDemoR1/Genesys2_VideoDemoR1.srcs/sources_1/ip/dpti_clock/dpti_clock.xci
# IP: The module: 'dpti_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Dropbox/physics/UdeC/FPGA_UBB/Final_FPGA_UBB/Genesys2_VideoDemoR1/Genesys2_VideoDemoR1.gen/sources_1/ip/dpti_clock/dpti_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpti_clock'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/danie/Dropbox/physics/UdeC/FPGA_UBB/Final_FPGA_UBB/Genesys2_VideoDemoR1/Genesys2_VideoDemoR1.gen/sources_1/ip/dpti_clock/dpti_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpti_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/danie/Dropbox/physics/UdeC/FPGA_UBB/Final_FPGA_UBB/Genesys2_VideoDemoR1/Genesys2_VideoDemoR1.gen/sources_1/ip/dpti_clock/dpti_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpti_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/danie/Dropbox/physics/UdeC/FPGA_UBB/Final_FPGA_UBB/Genesys2_VideoDemoR1/Genesys2_VideoDemoR1.srcs/sources_1/ip/dpti_clock/dpti_clock.xci
# IP: The module: 'dpti_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Dropbox/physics/UdeC/FPGA_UBB/Final_FPGA_UBB/Genesys2_VideoDemoR1/Genesys2_VideoDemoR1.gen/sources_1/ip/dpti_clock/dpti_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpti_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/danie/Dropbox/physics/UdeC/FPGA_UBB/Final_FPGA_UBB/Genesys2_VideoDemoR1/Genesys2_VideoDemoR1.gen/sources_1/ip/dpti_clock/dpti_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpti_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/danie/Dropbox/physics/UdeC/FPGA_UBB/Final_FPGA_UBB/Genesys2_VideoDemoR1/Genesys2_VideoDemoR1.gen/sources_1/ip/dpti_clock/dpti_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpti_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
